openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "API Docs"
servers:
  - url: "http:/localhost:5000"
    description: "Local server"
components:
security:
paths:
  /test:
    get:
      summary: "Runs a test request against the Identity Server demo API"
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"